stella-emu/stella

- src/emucore/CartDPCPlus.cxx
- src/emucore/CartDPCPlus.hxx
- src/emucore/Thumbulator.cxx
- src/emucore/Thumbulator.hxx
Implemented ARM Timer 1 support in Thumbulator.  Revised DPC+ to use it.
> ARM Timer 1 support

- src/common/Base.cxx
- src/common/Base.hxx
- src/debugger/gui/CartBUSWidget.cxx
- src/debugger/gui/CartBUSWidget.hxx
- src/debugger/gui/CartCDFWidget.cxx
- src/debugger/gui/CartCDFWidget.hxx
- src/emucore/Cart.cxx
- src/emucore/Cart.hxx
- src/emucore/CartBUS.cxx
- src/emucore/CartBUS.hxx
- src/emucore/CartCDF.cxx
- src/emucore/CartCDF.hxx
- src/emucore/CartDPCPlus.cxx
- src/emucore/Thumbulator.cxx
- src/emucore/Thumbulator.hxx
- src/macosx/stella.xcodeproj/project.pbxproj
Preliminary support for new Harmony/Melody drivers BUS and CDF.  Work remains for the 3-Voice Audio, Digital Sample playback, and some additional revisions to the debugger widgets.
> Preliminary support for BUS and CDF

- src/debugger/gui/CartBUSWidget.cxx
- src/emucore/CartBUS.cxx
- src/emucore/CartBUS.hxx
Add digital sample support to BUS.
> Updates to BUS

- src/emucore/CartBUS.cxx
- src/emucore/CartCDF.cxx
- src/emucore/CartDPCPlus.cxx
Christian discovered a bug in the updateMusicModeDataFetchers() function used by BUS, CDF, and DPC+.
> 3 voice music correction

- src/debugger/gui/CartCDFWidget.cxx
- src/debugger/gui/CartCDFWidget.hxx
- src/debugger/gui/CartDebugWidget.hxx
- src/debugger/gui/CartRamWidget.cxx
- src/debugger/gui/DataGridWidget.cxx
- src/debugger/gui/DataGridWidget.hxx
- src/debugger/gui/RamWidget.cxx
- src/emucore/CartCDF.cxx
- src/emucore/CartCDF.hxx
* Implemented load/save state.
* Updated the debugger tab, which required the following:
- removal of : from RAM labels (part of the debugger overhaul)
- setCrossed() functionality in the DataGrid
> CDF updates

- src/emucore/CartCDF.cxx
- src/emucore/CartCDF.hxx
Revised CDF so "false" reads after NOPs, taken branch instructions, etc. no longer crash JMP FASTJMP
> Update to CDF FastJump

- src/emucore/EventHandler.cxx
Found this accidentally while making snapshots of Aardvark
> Corrected wrong message "shotshot" to "snapshot"

- configure
Signed-off-by: Sergio Prado <sergio.prado@e-labworks.com>
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[Retrieved (and slightly updated) from:
https://git.buildroot.net/buildroot/tree/package/stella/0001-Add-cross-compilation-support.patch]
> Add cross-compilation support

- src/libretro/StellaLIBRETRO.hxx
- src/libretro/libretro.cxx
RetroPad: paddles (4), driving (2), booster (2)
> libretro: handle more controllers

- src/emucore/M6532.hxx
- src/libretro/StellaLIBRETRO.hxx
- src/libretro/libretro.cxx
http://retroachievements.org/gameList.php?c=25
> libretro: add achievements

- src/emucore/M6532.hxx
- src/libretro/StellaLIBRETRO.cxx
- src/libretro/StellaLIBRETRO.hxx
use shadow ram copy for frontend
> libretro: make getRAM const

- src/libretro/Makefile.common
- src/libretro/Stella.vcxproj
> libretro: add project file

- src/libretro/Makefile
Maybe this will work better for msvc?
Based off PR https://github.com/stella-emu/stella/pull/440.
> libretro: fix msvc makefile

- src/libretro/Makefile
This copies the solution for the osx build which failed the same way. Lets see how this goes...
> libretro: Attempt to fix the ios build.

- .travis.yml
- appveyor.yml
https://ci.appveyor.com
https://travis-ci.com/
> CI building

- src/gui/TimeMachineDialog.cxx
> Another spelling fix ("toggle")

- .gitlab-ci.yml
- src/libretro/Makefile
HI there,
I would really appreciate if this could be merged soon. It adds several platforms to build for on our Gitlab server.
Thanks in advance.
> (Libretro) Add more platforms to gitlab

- src/emucore/CartMVC.cxx
Output is much tidier as a solid square.
> Remove partial top and bottom line for square area

- .github/workflows/build.yml
This ensures that commits get a checkmark if they pass all tests.
> Run the build GHA on pushes as well as PRs

- src/emucore/CartMVC.cxx
Better behavior when shuttling to the beginning or end of the movie, including hitting exact frame, showing matching fields, and muting buzz.
> Reach first/last movie frame, show both fields and mute.

- src/emucore/CartMVC.cxx
When file not found, stay in title screen, else crashes / invalid data.
> MVC: Stay in title mode when valid file not found.

- src/os/libretro/libretro.cxx
- Enable reload/next game option in Core options
- Map reload/next game action to X button
> libretro: add reload/next game
