src/macosx/AboutBox.h
src/macosx/AboutBox.m
src/macosx/Preferences.m

Use UTF-8 for saving/getting preferences: It's more reliable.
Retain defaults in the Preferences Objective-C class.
Fill out the types for the IBOutlet

More Mac improvements:

---

src/emucore/tia/PaddleReader.cxx
src/emucore/tia/PaddleReader.hxx

The uClibc-ng C library defines a type called R0 when compiling for ARM,
that conflits with a global variable called R0 from PaddleReader.cxx.
src/emucore/tia/PaddleReader.cxx:25:3: error: ‘constexpr const double R0’ redeclared as different kind of symbol
R0 = 1.5e3,
^
/home/sprado/workspace/build/buildroot/build/stella_uclibc/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/include/sys/ucontext.h:42:3: note: previous declaration ‘<anonymous enum> R0’
R0 = 0,
^~
So let's redefine R0 as a private member of the PaddleReader class.
Signed-off-by: Sergio Prado <sergio.prado@e-labworks.com>

Fix error when building with uClibc-ng for ARM

---

src/debugger/CartDebug.cxx

Wrong operator precedence was used : pos was assigned the comparision of the search for '.' with string::npos, giving 1. Hence, only first character of local label was stripped instead of everything up to the first dot.

Fixed removal of prefix of local labels (global.local -> .local).

---

Changes.txt
docs/debugger.html
src/debugger/gui/RamWidget.cxx
src/emucore/Settings.cxx

* commmands -> commands
* comparitive -> comparative
These were found by Debian’s Lintian tool.

Spelling fixes

---

src/debugger/DebuggerParser.cxx
src/debugger/DebuggerParser.hxx
src/debugger/gui/TiaOutputWidget.cxx
src/debugger/gui/TiaOutputWidget.hxx

This pull request adds 10 new debugger commands to manipulate programmatically the state of the controller inputs. These commands are supposed to be used from debugger scripts (using `exec`). The names of the commands are similar to the built-in debugger functions.

Add debugger commands to manipulate controller state.

---

configure

If user specifies CXX, use it as-is, since that's the user's choice.
Closes #292

Fix overriding CXX setting

---

Makefile

Signed-off-by: Sergio Prado <sergio.prado@e-labworks.com>
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[Retrieved from:
https://git.buildroot.net/buildroot/tree/package/stella/0002-Do-not-strip-when-installing.patch]

Do not strip when installing

---

src/libretro/Makefile.common

It now builds here again with 64-bit linux.
See: 
https://github.com/stella-emu/stella/issues/377#issuecomment-488553546
https://github.com/stella-emu/stella/commit/d8f28f19cee08f5c00dc306fae6a5072054030f9

libretro: Fix linux build.

---

src/libretro/Makefile

Seems the last fix for moving `-Wextra` worked, but now its stuck on `-Wno-unused-parameter` instead. This might take a few attempts...
```
make: *** [Makefile:656: ../libretro/libretro.o] Error 2
cl : Command line error D8021 : cl : Command line error D8021 : cl : Command line error D8021 : cl : Command line error D8021 : invalid numeric argument '/Wno-unused-parameter'invalid numeric argument '/Wno-unused-parameter'invalid numeric argument '/Wno-unused-parameter'invalid numeric argument '/Wno-unused-parameter'
```

libretro: Another fix for msvc.

---

src/libretro/Makefile

We're making progress, slowly...
```
cl : Command line error D8021 : invalid numeric argument '/Wno-ignored-qualifiers'
make: *** [Makefile:656: ../libretro/libretro.o] Error 2
```

libretro: Yet another fix for msvc.

---

src/libretro/Makefile.common

This removes `-I../libretro/SDL`, `-I../libretro/libpng` and `-I../libretro/zlib` from libretro's `Makefile.common`. I don't think the libretro core uses these anymore and the paths are not valid. It builds without issue here on linux at least.

libretro: Remove unused include paths.

---

src/libretro/Makefile

This an attempted fix for the osx buildbot, I notice the standalone stella already seems to use this for osx.
Reference: https://stackoverflow.com/questions/10116724/clang-os-x-lion-cannot-find-cstdint/10116753#10116753
Note I think this will only work with clang, but I understand that is already advisable on osx with stella and the libretro buildbot is already using clang. Some other libretro makefiles seem to be doing this for osx as well.
```
In file included from ../libretro/EventHandlerLIBRETRO.cxx:18:
../emucore/OSystem.hxx:45:10: fatal error: 'chrono' file not found
#include <chrono>
^
In file included from ../libretro/libretro.cxx:15:
In file included from ./StellaLIBRETRO.hxx:21:
../common/bspf.hxx:29:10: fatal error: 'cstdint' file not found
#include <cstdint>
^
1 error …
```

libretro: Attempted fix for osx.

---

src/libretro/Makefile

My previous PR (https://github.com/stella-emu/stella/pull/448) was wrong, I should of looked closer instead of trying to copy other makefiles. This clearly needs to be in `CXXFLAGS`.

libretro: Attempt to fix osx again.

---

src/libretro/Makefile

The last build from the libretro buildbot had a new issue as a result to my previous PR (https://github.com/stella-emu/stella/pull/449).
```
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
make: *** [../libretro/EventHandlerLIBRETRO.o] Error 1
```
It was suggested in #libretro @ freenode by Twinaphex to try setting this line to `10.7`. Hopefully this will help.

libretro: Try setting osx to 10.7.

---

src/libretro/Makefile
src/libretro/Makefile.common

The libretro Makefile is honestly a mess right now and I'd like to spend some time cleaning it up so lets start with removing some unusued stuff.
Note my assumption is that stella is a c++ program and any c code would be external dependencies which the libretro core does not depend on anymore.

libretro: Remove CFLAGS and CC from the Makefile.

---

src/libretro/Makefile

The last two PRs (https://github.com/stella-emu/stella/pull/449 and https://github.com/stella-emu/stella/pull/450) made progress, now osx is failing on linking with many undefined c++ references. I am thinking it probably needs `-stdlib=libc++` in the `LDFLAGS` too?
For reference see this log.
[stella-osx-x64-generic.log](https://github.com/stella-emu/stella/files/3142107/stella-osx-x64-generic.log)

libretro: Add -stdlib=libc++ to the LDFLAGS for osx too.

---

src/libretro/Makefile

This should have no changes in behavior and I did two things.
1. The Makefile is full of both tabs and inconsistent spacing, this make it much harder to read and I changed everything that I could to use three spaces as is standard in libretro projects. If other styles are preferred I can do that.
2. I removed a few redundant variables I noticed while doing the former, for example `LIB` was set to the same value in some places.

libretro: Fix identing in the Makefile.

---

src/libretro/Makefile

Instead of disabling them one by one I found some documentation.
Reference: https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=vs-2019
Not surprisingly the only ones listed in this list are `-Wall` and `-std`...
For reference here is the current error.
```
cl : Command line error D8021 : invalid numeric argument '/Wunused'
make: *** [Makefile:591: ../libretro/libretro.o] Error 2
make: *** Waiting for unfinished jobs....
make: *** [Makefile:591: ../libretro/EventHandlerLIBRETRO.o] Error 2
```

libretro: Hide compiler options from msvc.

---

src/emucore/Paddles.cxx

Fixes the libretro build which is broken again on at least linux, mingw and osx.
```
../emucore/Paddles.cxx: In member function ‘virtual void Paddles::update()’:
../emucore/Paddles.cxx:269:27: error: ‘pow’ is not a member of ‘std’
269 |     double dFactor = std::pow(factor1, 1 / (abs(sa_xaxis - myLastAxisX) * factor2));
|                           ^~~
../emucore/Paddles.cxx:278:27: error: ‘pow’ is not a member of ‘std’
278 |     double dFactor = std::pow(factor1, 1 / (abs(sa_yaxis - myLastAxisY) * factor2));
|                           ^~~
make: *** [Makefile:591: ../emucore/Paddles.o] Error 1
```

libretro: Fix build.

---

src/libretro/Makefile

With `clang-8.0.0` on linux the libretro compile will warn many times.
```
clang-8: warning: -lpthread: 'linker' input unused [-Wunused-command-line-argument]
```
I think `-lpthread` is just for linking and not useful for compiling so I updated the libretro makefile accordingly.
Reference: https://stackoverflow.com/questions/23250863/difference-between-pthread-and-lpthread-while-compiling
I did this only for unix which I can test.

libretro: Silence clang warnings for unix.

---

src/libretro/Makefile

Hi there,
with this buildfix, the MSVC 2017 libretro targets should compile again. This can help us out immensely on the buildbot.

(Libretro/MSVC 2017) Buildfix

---

configure

This simplifies the interpretation of GCC versions, and handles all
versions greater than 4, hopefully for good.
Fixes: #590

Handle GCC versions after 9

---

docs/index.html

The list of presets includes an extra quote in "low quality, medium
lag"; this patch removes it.

Remove extra quote for audio presets

---

.gitlab-ci.yml

Hi there,
we are migrating to a new build server infrastructure. This file will help ensure that each commit triggers a recompile on our buildservers for Libretro. As an additional side bonus, it will help inform if all builds have succeeded per commit for libretro.

Create .gitlab-ci.yml - for new Libretro build infrastructure

---

src/libretro/libretro.cxx
src/libretro/libretro.h

I've noticed that while input bitmasks have been implemented in libretro's fork of Stella 3.9.3, they're still not implemented in mainline Stella, so here's my attempt.  More information: https://github.com/libretro/RetroArch/issues/11217.

Implemented input bitmasks

---

src/libretro/Makefile

Since 6.1.1, compiling the libretro core has required static libgcc and libstdc++, meaning you either have to have them installed or edit the Makefile.  Well, this PR checks whether the static versions are available on the system and only uses them if they are.  I had considered other methods, like a variable, but I like this way because it's automatic.

(libretro) [unix] Only use static libgcc/libstdc++ if they're present

---

src/libretro/Makefile

Hi, this is necessary for the iOS 9 libretro core to build on our Gitlab server. Currently any attempt to build it either locally or on the server would result in an error, this fixes it.

(Libretro) Fix ios9 build

---

src/libretro/Makefile

Hi there, I'd much appreciate if this could get merged. This should fix the ARM64 libretro core for macOS.

(Libretro/macOS) Add ARM64 rules

---

src/common/PJoystickHandler.cxx

For some controllers, the initial default (i.e. when the controller
is first attached) mappings seem to not work in emulation mode, but
work just fine in menu mode. The emulation mode mappings are shown
in the UI, but do not work until the second time the emulator is
started.
From debugging, even in emulation mode the joyMap is returning
menu bindings when in-game. Fix this bug by adding the emulation
mode mappings before the menu mode mappings.
Fixes: a7189ce7ec6f ("fix attempt for #692")
Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>

joystick: Add menuMode mappings before emulationMode mappings

---

src/emucore/Driving.cxx
src/emucore/Event.hxx

- Use a float divisor to reduce the high resolution counter to a gray
code. This gives a more stable rate of change for the gray code when
using a sensitivity other than 1.
- Slightly remap the axis space, so that the positive and negative
ranges are the same. The new range is [64,-1] [1, 64]. We don't need
zero, because of the analog dead zone.
- Reorder the Event enum as suggested for on PR860.
Contains some of the suggested changes arising from #860

Fixes for driving mode changes

---

src/gui/EventMappingWidget.cxx

Reorder "Driving" within the event mapping widget

---

docs/index.html

The default keybindings remain the same as they did, they are just no longer shared with the Joystick Mode.

Update documentation for keybindings in Driving Mode

---

src/common/PJoystickHandler.cxx
src/common/PJoystickHandler.hxx
src/emucore/Paddles.cxx
src/emucore/Paddles.hxx

Map paddles to distinct controllers. For two player games, having both players share a single controller isn't ideal. Instead, put
- Left A -> joystick 0
- Left B -> joystick 1
- Right A -> joystick 2
- Right B -> joystick 3
and support up to four players with four controllers. This mostly amounts to having distinct defaults for each paddle, and untangling some of the internals.

Paddle mode enhancements

---

src/gui/Stella12x24tFont.hxx
src/gui/Stella14x28tFont.hxx
src/gui/Stella16x32tFont.hxx
src/gui/Terminus-Font-License.txt

src/gui/Stella*tFont.hxx are derived from the Terminus font, whose
license requires the full copyright notice and license to be provided
with original or modified versions of the font.
This adds the missing information.

Add Terminus font licensing information

---

.github/workflows/build.yml

This reproduces the Appveyor build for 32- and 64-bit Windows.

Add a GitHub action to build on Windows

---

.github/workflows/build.yml

This bumps actions/checkout to v3.1.0 and microsoft/setup-msbuild to v1.1.3, which switch to environment files. See
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for context and
https://github.com/actions/checkout/releases/tag/v3.1.0 and https://github.com/microsoft/setup-msbuild/releases/tag/v1.1.3 for details of the changes.

Upgrade GHAs to drop save-state and set-output

---

.github/workflows/build.yml

This avoids warnings about apt's suitability for use in scripts.

Use apt-get instead of apt

---

src/os/libretro/libretro.cxx

fixes #949 and returns input to Elevator Agent game.
I just did brief testing with Elevator Agent, so I don't know if this would have any farther reaching implications for other games. Just let me know if so.

add Joy2B+ support to libretro

---

src/emucore/tia/Audio.cxx
src/emucore/tia/Audio.hxx
src/emucore/tia/AudioChannel.cxx
src/emucore/tia/AudioChannel.hxx

volume of audio channels sampled every on every tick. sum of samples is averaged and a new sample output twice per scanline
this fixes issues with ROMs that change the volume of the audio multiple times per scanline. for example, the experimental ROM in the following thread now works correctly
https://forums.atariage.com/topic/370460-8-bit-digital-audio-from-2600/
(note that the ROM does not initialise the machine cleanly and so running the emulator with developer options (random memory etc.) can cause incorrect audio)

Improvement to volume sampling in TIA audio

---

.gitlab-ci.yml
src/os/libretro/Makefile

The Android builder seems to only go up through c++2a; it fails when trying to `#include <numbers>`. Hopefully I can come back to this at some point.
Nintendo Switch seems to have proper C++20 support except that `strnlen` isn't defined? Also the Docker container does not seem to be building for me so I can't test it locally to see why not. Hopefully I can also come back to this at some point.

libretro: fix gitlab CI

---

.gitignore
debian/control

Found this one when trying to build on Raspberry Pi.

Debian build requires libgtest-dev, but is not specified

---

configure

stella fails to cross build from source on Unix-style platforms, because ./configure hard codes the build architecture pkg-config and thus fails finding libraries. It already has a bit of knowledge about cross compilation and actually considers a _host_prefix for some tools. Unfortunately, _host_prefix is not yet generally initialized and it also does not prepend _host_prefix to pkg-config.
This fixes these issues.
Forwarded from https://bugs.debian.org/1094710.

Detect _host_prefix and allow cross pkg-config
